import requests
import json
import time

# Use your Mac's IP address that we found earlier
BACKEND_URL = "http://172.16.149.247:8000/rover/scan"

# Mock data generated by the "Jetson AI"
jetson_ai_output = {
    "image_url": "https://images.unsplash.com/photo-1592841200221-a6898f307baa?q=80&w=800&auto=format&fit=crop",
    "plant_name": "Cotton",
    "disease": "Boll Rot",
    "severity": "Critical",
    "confidence": "94%",
    "medicine": "Copper Oxychloride 50% WP",
    "location": "Sector D, Row 8"
}

print("🤖 Jetson Nano Initialized. Scanning field...")
time.sleep(2)
print("⚠️ Disease detected! Sending telemetry to Kisansathi Server...")

try:
    response = requests.post(BACKEND_URL, json=jetson_ai_output)
    if response.status_code == 201:
        print("✅ Data successfully saved to MongoDB!")
        print("Server Response:", response.json())
    else:
        print("❌ Error:", response.status_code, response.text)
except Exception as e:
    print("❌ Connection Failed:", e)